spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: smoke-weather
      auto-index-creation: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      topic: my-Topic