spring:
  profiles:
    active: ${PROFILE_ACTIVE:local}
  application:
    name: smoke-weather-api
  mvc:
    servlet:
      path: /api/v1
server:
  port: 8080

open-meteo-api:
  url: ${OPEN_METEO_URL:https://api.open-meteo.com/v1/}